"""Generate docs/02_parameter_database.md from config/watch.yaml + the derived registry.

Single source of truth: the tables are regenerated, never hand-edited.
Author: Anwesh Ajitabh Dash
"""
from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from twin.model import build_model  # noqa: E402
from twin.params import load_params  # noqa: E402

BADGE = {"measured": "MEASURED", "sourced": "SOURCED", "inferred": "INFERRED", "assumed": "ASSUMED"}


def fmt(v):
    if isinstance(v, float):
        if v == 0:
            return "0"
        if abs(v) >= 1e4 or abs(v) < 1e-3:
            return f"{v:.4g}"
        return f"{v:.6g}"
    return str(v)


def main() -> str:
    P = load_params()
    M = build_model(P)
    bp = P.by_provenance()
    lines = ["# Parameter database", "",
             "_Generated by `tools/gen_param_docs.py` from `config/watch.yaml`. Do not edit by hand._", "",
             "## Provenance summary", "",
             "| Provenance | Meaning | Count |", "|---|---|---|"]
    meaning = {"measured": "Observed on the owner's watch (engraving, photo, photogrammetry, owner test)",
               "sourced": "Manufacturer / reference documentation (Miyota 82S0, Timex)",
               "inferred": "Derived from verified data via a stated constraint, or calibrated to a verified spec",
               "assumed": "Engineering estimate for this class of movement (configurable, with range)"}
    for k in ("measured", "sourced", "inferred", "assumed"):
        lines.append(f"| **{BADGE[k]}** | {meaning[k]} | {len(bp[k])} |")
    lines += ["", f"VERIFIED (measured + sourced): **{len(bp['measured']) + len(bp['sourced'])}** · "
              f"ESTIMATED (inferred + assumed): **{len(bp['inferred']) + len(bp['assumed'])}**", ""]
    groups = defaultdict(list)
    for key, prm in P.items():
        groups[key.split(".")[0]].append(prm)
    lines += ["## Input parameters", ""]
    for g, prms in groups.items():
        lines += [f"### `{g}`", "", "| Parameter | Value | Unit | Provenance | Range | Source / rationale |",
                  "|---|---:|---|---|---|---|"]
        for p in prms:
            rng = f"{fmt(p.range_raw[0])} – {fmt(p.range_raw[1])}" if p.range_raw else ""
            lines.append(f"| `{p.key.split('.', 1)[1]}` | {fmt(p.raw)} | {p.unit} | {BADGE[p.prov]} | {rng} | {p.src} |")
        lines.append("")
    prov = M.reg.provenance(P)
    lines += ["## Derived quantities (computed, with governing equations)", "",
              "| Quantity | Value | Unit | Equation | Basis |", "|---|---:|---|---|---|"]
    for d in M.reg.items.values():
        lines.append(f"| {d.name} | {fmt(d.display)} | {d.unit} | `{d.equation}` | {prov.get(d.name, '')} |")
    text = "\n".join(lines) + "\n"
    (ROOT / "docs" / "02_parameter_database.md").write_text(text, encoding="utf-8")
    return text


if __name__ == "__main__":
    t = main()
    print(t[:1500])
